version: '3'
services:
  web:
    build: .
    command: gunicorn myapp:app -b 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /app/static:/app/static
    depends_on:
      - web
