version: '3'
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
